version: '2'
services:

  redis:
    image: "redis:alpine"
    container_name: phantom-redis
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redis:/data'

  postgres:
    image: "postgres:alpine"
    container_name: phantom-postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
     POSTGRES_PASSWORD: password
     POSTGRES_DB: phantom_devnet
     POSTGRES_USER: phantom

  phantom-core:
    build: .
    image: phantom-core
    container_name: phantom-core
    ports:
     - "4002:4002"
     - "4003:4003"
    volumes:
     - phantom-core:/phantom-core
    tty: true
    privileged: true
    links:
     - postgres
     - redis
    depends_on:
      - postgres
      - redis
    command:
      - /bin/sh
      - -c
      - |
          /entrypoint.sh

volumes:
  redis:
  postgres:
  phantom-core:
    driver_opts:
      type: none
      device: $PWD/../../
      o: bind
